### ISSUE TITLE
Fill with init values

### ISSUE THREAD

**Issue by toxaV** [toxaV/LogViewer#1]
FIll table 100 records with prefilled data from local storage
Columns are 
[LogID] int 
[Severity] string (Information, Error, Warn)
[Title] string
[Timestamp] datetime
[MachineName] string
[ProcessName] string
[Message] string 
[FormattedMessage] string

---

Example: 

LogID 108  
Severity  Information  
Title    GetAccountInformation
Timestamp  2015-09-30 10:21:09.300
MachineName RD000D3AB02CD6
ProcessName d:\windows\system32\inetsrv\w3wp.exe
Message: Operation completed successfully
FormattedMessage
Priority: -1
EventId: 0
Severity: Information
Title:GetAccountInformation
Machine: RD000D3AB02CD6
App Domain: /LM/W3SVC/1273337584/ROOT-1-130880784533547167
ProcessId: 5292
Process Name: d:\windows\system32\inetsrv\w3wp.exe
Thread Name: 
Win32 ThreadId:5424
Extended Properties: Request - <?xml version="1.0" encoding="utf-16"?>
<GetAccountInformationRequestMessage xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <GetAccountInformationRequest>
    <ci>
      <locale>es-ES</locale>
      <country>ES</country>
      <channel>web</channel>
    </ci>
    <MSISDN xmlns="http://Lebara.BluePipe.Common.Schema.GetAccountInformationRequest">672844573</MSISDN>
    <UserType xmlns="http://Lebara.BluePipe.Common.Schema.GetAccountInformationRequest">PREPAY</UserType>
  </GetAccountInformationRequest>
</GetAccountInformationRequestMessage>
Response - <?xml version="1.0" encoding="utf-16"?>
<GetAccountInformationResponse xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://Lebara.BluePipe.Common.Schema.GetAccountInformationResponse">
  <Status xmlns="">SU</Status>
  <resultStatus xmlns="">
    <prepay>
      <creditBalance>208.26</creditBalance>
      <bundleDetails>
        <bundleType>2536</bundleType>
        <bundleDescription>SP Free Credit</bundleDescription>
    Timestamp: 9/30/2015 9:21:09 AM

Message: Timestamp: 9/30/2015 9:21:08 AM
Message: Operation completed successfully
Category: 
Priority: -1
EventId: 0
Severity: Information
Title:GetAccountInformation
Machine: RD000D3AB02CD6
App Domain: /LM/W3SVC/1273337584/ROOT-1-130880784533547167
ProcessId: 5292
Process Name: d:\windows\system32\inetsrv\w3wp.exe
Thread Name: 
Win32 ThreadId:5424
Extended Properties: Request - <?xml version="1.0" encoding="utf-16"?>
<GetAccountInformationRequestMessage xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <GetAccountInformationRequest>
    <ci>
      <locale>es-ES</locale>
      <country>ES</country>
      <channel>web</channel>
    </ci>
    <MSISDN xmlns="http://Lebara.BluePipe.Common.Schema.GetAccountInformationRequest">672844573</MSISDN>
    <UserType xmlns="http://Lebara.BluePipe.Common.Schema.GetAccountInformationRequest">PREPAY</UserType>
  </GetAccountInformationRequest>
</GetAccountInformationRequestMessage>
Response - <?xml version="1.0" encoding="utf-16"?>
<GetAccountInformationResponse xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://Lebara.BluePipe.Common.Schema.GetAccountInformationResponse">
  <Status xmlns="">SU</Status>
  <resultStatus xmlns="">
    <prepay>
      <creditBalance>208.26</creditBalance>
      <bundleDetails>
        <bundleType>2536</bundleType>
        <bundleDescription>SP Free Credit</bundleDescription>
        <bundleExpiryDate>2015-10-22</bundleExpiryDate>
        <bundleRemaining>4.13</bundleRemaining>
        <bundleID>2536</bundleID>
        <bundleUnit>Euro</bundleUnit>
      </bundleDetails>
      <bundleDetails>
        <bundleType>5197</bundleType>
        <bundleDescription>SP L2L Voice_PSP</bundleDescription>
        <bundleExpiryDate>2015-10-23</bundleExpiryDate>
        <bundleRemaining>1500</bundleRemaining>
        <bundleID>5197</bundleID>
        <bundleUnit>Minute</bundleUnit>
      </bundleDetails>
      <isRoamingActivate>false</isRoamingActivate>
    </prepay>
  </resultStatus>
  <TopUpPending xmlns="">false</TopUpPending>
</GetAccountInformationResponse>

Category: TraceAll

Priority: 0

EventId: 0

Severity: Information

Title:GetAccountInformation

Machine: RD000D3AB02CD6

App Domain: /LM/W3SVC/1273337584/ROOT-1-130880784533547167

ProcessId: 5292

Process Name: d:\windows\system32\inetsrv\w3wp.exe

Thread Name: 

Win32 ThreadId:5424

Extended Properties:

**Comment by max-klimm** [comment]
created 100 rows in the table
